### PR TITLE
fix: the sample pages

### PR DESCRIPTION
**Pull request by baseonmars**
Sample pages were not loading, as result of importing haml needs to be cast to a string when not passed through the translation helper.

This is due to the the default export of the haml–loader not being recognised as a string by the HTML Storybook App (it's an augmented string object but it's still a string deep down inside!)

### CODE REVIEW

**Review by davidrapson — CHANGES_REQUESTED** [review]
👍 Cool beans, although I think we can remove this from the changelog (as it doesn't affect the published package) and instead run `npm run docs:build` and commit those changes here. We only need to fix the github pages build right?

**Review by davidsauntson — APPROVED** [review]
🧶 
might be worth adding the sample pages into VRT but not in this PR if want to get the fix in ASAP.

**Comment by baseonmars** [comment]
> 👍 Cool beans, although I think we can remove this from the changelog (as it doesn't affect the published package) and instead run `npm run docs:build` and commit those changes here. We only need to fix the github pages build right?

I guess so... cool beans.

**Review by davidrapson — APPROVED** [review]
image

**Review by davidrapson — APPROVED** [review]
🚀

**Pull request merged**
