### PR TITLE
bugfix: Mac Firefox click issue (Exclude tests) [NP-851]

### PR DESCRIPTION
**Pull request by luke-hill**
Finally triaged this down to being a legit bug. NP-852 has been created to track / fix this issue. Meanwhile this PR excludes these tests from being ran whilst this issue is investigated. This should help fix our CI being back to :green_book: 

NP-852 contains all relevant info and a movie from Marcelo detailing the issue (clickEvents not firing).

### CODE REVIEW

**Comment by panosvoudouris** [comment]
As this is a legitiamte bug should we not just leave the tests there and fix the bug instead? This is not really blocking anything right now.

**Comment by luke-hill** [comment]
We can do I don't mind @panosvoudouris How hard is it to fix the bug? Is this something we should fix now?

**Comment by panosvoudouris** [comment]
I'm starting work on it now, should have it sorted today/tomorrow.

**Review by celonicolosi — APPROVED** [review]
LGTM

**Comment by panosvoudouris** [comment]
Don't merge this, I've got a fix coming in a bit.

**Comment by panosvoudouris** [comment]
Fixed with #218

**Pull request closed without merging**
