### PR TITLE
feat: bad haml

### PR DESCRIPTION
**Pull request by davidsauntson**
testing that we can't merge a PR where the github actions fail

### CODE REVIEW

**Comment by simonwgill** [comment]
You don't have automerge set up on this repo, do you? This looks suspiciously like it will allow a merge if @davidrapson reviews it

**Comment by davidsauntson** [comment]
> You don't have automerge set up on this repo, do you? This looks suspiciously like it will allow a merge if @davidrapson reviews it

We don't - and yes it does look like that so that's what I wanted to test.  Will see when @davidrapson  approves it

**Review by davidrapson — APPROVED** [review]
I have no standards, lgtm

**Comment by davidrapson** [comment]
That's better. Thanks @simonwgill!

image

**Comment by davidsauntson** [comment]
👏🏻

**Pull request closed without merging**
