### PR TITLE
Remove legacy haml partials

### PR DESCRIPTION
**Pull request by davidrapson**
We've been using the citizens_advice_components gem for all components for a while now. We're probably at the point where keeping the legacy haml partials around is limiting as we make more and more changes to view components.

### CODE REVIEW

**Comment by davidrapson** [comment]
One to discuss tomorrow. Only thing I noticed whilst doing this is that we're missing view component docs for callouts.

**Comment by davidsauntson** [comment]
Yeah fine - this will take us to 5.0.0 according to the roadmap.

**Comment by davidrapson** [comment]
> Yeah fine - this will take us to 5.0.0 according to the roadmap.

Makes sense. As we're also looking at the SVG icons and other new components now feels like the time to do that.

**Review by davidsauntson — APPROVED** [review]
🔥

**Pull request merged**
