### PR TITLE
feature: Button Audit [NP-2113]

### PR DESCRIPTION
**Pull request by luke-hill**
Added simple spec to validate link button w3c props

### CODE REVIEW

**Review by davidrapson — COMMENTED** [review]
Interesting. The button "component" is really a single set of class names and there's not a distributed template for them. You can also legitimately use the classes on a range of different types. More so for the regular `cads-button` class but the point still stands.

So "correct" type for all these button specs is really very contextual and down to usage. All this test will do is assert that the docs have a button with type `button`. Not sure this test tells us much. Wonder if these sorts of checks are better scoped to tests in products themselves?

**Comment by luke-hill** [comment]
Hmmm interesting. Doesn't that mean then that it would fail a11y checks down the line? Also these tests already existed so I just updated them as per the audit tasks I had created.

What do you advise here? I'd like something in here, even if it's rudimentary as I'm trying to cover all the components/forms as the tests run subsecond.

**Review by davidrapson — APPROVED** [review]
> Doesn't that mean then that it would fail a11y checks down the line?

It depends on usage. I guess bear in mind that these are fundamentally just a set of CSS styles. So what semantics are used are down to individual projects. In this case our docs aim to pave the path.

Approving and will leave the call to you. This test is ultimately pretty harmless.

**Comment by luke-hill** [comment]
It's a good point you raise. I'll merge for now, but yeh this is a good learning point for me. Thanks for the context.

**Pull request merged**
