### PR TITLE
Fix/error summary np 1979

### PR DESCRIPTION
**Pull request by davidsauntson**
Removes issue count and technical language (`fields`) from the error summary partial, example, docs and tests.

### CODE REVIEW

**Comment by luke-hill** [comment]
How come this is needed? I always thought this was a good thing? Is it not?

**Comment by minniessuyuhuang** [comment]
> How come this is needed? I always thought this was a good thing? Is it not?

@luke-hill You can find the full details in this ticket: https://citizensadvice.atlassian.net/browse/NP-1979?atlOrigin=eyJpIjoiNjgzMTVmNmIyM2UxNGQxMGI1YzZkNGM2ZmRkYzNlZGUiLCJwIjoiaiJ9

**Comment by luke-hill** [comment]
Wow oki. That's really interesting, as most of the out-of-the-box stuff (In many languages, not just ruby), uses the numerical thing to try help people work out how many things to fix. It's fine by me. Probably should be signed off by someone in the know though.

**Review by minniessuyuhuang — APPROVED** [review]

**Review by davidrapson — APPROVED** [review]
👍 Looks good to me

@luke-hill For context, this change was already made to how we show things on public-website. So this change is mostly making sure the component and documentation is  accurate and up to date on this design system side.

**Pull request merged**
