### PR TITLE
Enable network logs same as PW

### PR DESCRIPTION
**Pull request by luke-hill**
Ronseal PR. Same as PW mirror PR.

### CODE REVIEW

**Comment by davidrapson** [comment]
Where are we sending the network logs?

**Comment by luke-hill** [comment]
These are the network logs available by hitting f12 and clicking network. They're being sent as an additional silent capture (So they'd be available via REST, and via the BS interface).

**Comment by davidrapson** [comment]
Just seen the public website equivalent. If this is for debugging a specific device type could we limit the network logging to just that?

**Comment by luke-hill** [comment]
It's for a few different device combinations. Few older versions of chrome. iOS e.t.c.

**Review by davidrapson — APPROVED** [review]
👍 Although it would be great to set a date to remove this, or add a comment explaining what we are using them for so we don't forget to disable this afterwards.

**Pull request merged**
