### PR TITLE
feat: add pointer to dropdown toggle, decouple border color

### PR DESCRIPTION
**Pull request by davidsauntson**
Add pointer to hover on nav more button
Decouple nav border hover colour from link text hover colour

### CODE REVIEW

**Review by baseonmars — COMMENTED** [review]
👆

**Review by baseonmars — APPROVED** [review]
👆👇👈👉

**Comment by davidrapson** [comment]
☝️ ☝️ 👇 👇 👈 👉 👈 👉 🅱️ 🅰️

**Comment by davidsauntson** [comment]
you've both lost your minds ❤️

**Pull request merged**
