### PR TITLE
Update local backstop version

### PR DESCRIPTION
**Pull request by davidrapson**
Local backstop versions were out of date with the package version. Also adds a dependabot config to keep this up to date in future.

### CODE REVIEW

**Comment by luke-hill** [comment]
Only thing to bare in mind with this is that @simonwgill looked into this recently, something about dockerfiles. Not sure if same thing.

**Review by baseonmars — COMMENTED** [review]
Any idea what the breaking change was between 4 and 5? Their release notes are pretty bare.

**Comment by davidrapson** [comment]
FWIW the docker files are already running v5

**Comment by davidrapson** [comment]
Ideally though I'd get rid of this and only use the docker image as that's always how we run it

**Comment by simonwgill** [comment]
It's in `bin/docker/visual_regression` and `bin/docker/rebuild_vr_references` - those scripts will select the backstopjs version referenced by the root package.json for that run. If the environment variable isn't set, it'll just use latest instead.

**Comment by davidrapson** [comment]
Interesting the _root_ package.json doesn't reference backstop at all. Can we get rid of this nested version and pin the docker version to v5? Or latest?

**Comment by simonwgill** [comment]
> Interesting the _root_ package.json doesn't reference backstop at all. Can we get rid of this nested version and pin the docker version to v5? Or latest?

So, what I didn't realise was happening was that `npm view $package version` gets the version from the global index. Technically it will always be the latest version getting downloaded by docker-compose then.

I wouldn't pin it to latest (despite my having accidentally done so) because there is a chance of tests just randomly starting to fail for no good reason.

**Comment by davidrapson** [comment]
Ah yeah I missed that. `npm view` looks up a package from the registry. Does tagging it to the latest released version in one place work e.g. `backstopjs/backstopjs:5.0.6`?

**Comment by simonwgill** [comment]
Yeah, if you take out the BACKSTOPJS_VERSION stuff which is completely useless, you can just use the version pin in the docker-compose file. Unless there's a sensible way of getting the version from the lock file?

Pinning in docker-compose would mean that we have to make a config change for every patch version update we wanted unfortunately. There's no major or major.minor tags on the backstopjs image repo.

**Comment by davidrapson** [comment]
> Pinning in docker-compose would mean that we have to make a config change for every patch version update we wanted unfortunately. There's no major or major.minor tags on the backstopjs image repo.

I think that is fine for this case as backstop release cadence is fairly slow. Plus if we get dependabot updating the package file at least that's a signal when it updates (unless there is a way for dependabot to update Docker file too?)

**Comment by davidrapson** [comment]
Updated this now

**Comment by simonwgill** [comment]
> > Pinning in docker-compose would mean that we have to make a config change for every patch version update we wanted unfortunately. There's no major or major.minor tags on the backstopjs image repo.
> 
> I think that is fine for this case as backstop release cadence is fairly slow. Plus if we get dependabot updating the package file at least that's a signal when it updates (unless there is a way for dependabot to update Docker file too?)

Not sure I understand your meaning of "plus" here, David. If we don't reference backstopjs in the package.json then I can't see how dependabot will fire for it? If there's a way to get it to update docker tags in a docker-compose file though, that would work out well.

**Comment by davidrapson** [comment]
We do, see testing/package.json and the new dependabot config I added.

**Comment by simonwgill** [comment]
Ahhh, gotcha.

So... this command works correctly to determine the backstopjs out of the package-lock in /testing/ `npm list backstopjs --depth=0 2>/dev/null | grep -i "backstopjs@" | grep -oEi "\d\.\d\.\d"`. It'll work whether or not the module is installed as well.

**Comment by davidrapson** [comment]
Going to come back to this as we need to review with Simons change and this isn't essential at the mo

**Pull request closed without merging**
