### PR TITLE
Fix/error summary scroll

### PR DESCRIPTION
**Pull request by marianayovcheva**
Original Issue:
https://github.com/citizensadvice/design-system/issues/1694
https://citizensadvice.atlassian.net/browse/NP-2423
> The links in the advice feedback form error summary link to the inputs so they get focus.  This means when you click on a link in the error summary you are scrolled to the top of the input and can see neither the error message or the field label.

Approach:
Using a [gov.uk's approach](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/error-summary/error-summary.mjs) as a base.

### CODE REVIEW

**Comment by davidrapson** [comment]
> For other components where we use a polyfill, we don't include the polyfill in the design system itself, we make a note on the component page and ask consumers to make sure they include it if they want to support older browsers (eg https://citizensadvice.github.io/design-system/?path=/docs/components-targeted-content--default#javascript-behaviour)

Not for this PR but I noticed working on https://github.com/citizensadvice/design-system/pull/2137 that we have another inline element.closest polyfill there too; so I should tidy that up too.

**Comment by davidrapson** [comment]
Sorry didn't mean to close this 🙈

**Comment by marianayovcheva** [comment]
Thanks! I've now removed the polyfill from the error summary. I think I'll keep the function as it is for now as when I've tried to adjust it locally I managed to make it less readable 😬

**Review by davidsauntson — APPROVED** [review]
🙌🏻

**Pull request merged**
